DROP DATABASE IF EXISTS quan_ly_ban_hang;
CREATE DATABASE quan_ly_ban_hang;
USE quan_ly_ban_hang;
CREATE TABLE customer(
cID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
cName VARCHAR(60) NOT NULL,
cAge INT
);
CREATE TABLE `order`(
oID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
cID INT NOT NULL,
oDate DATE,
oTotalPrice INT NOT NULL,
FOREIGN KEY(cID)
REFERENCES customer(cID)
);
CREATE TABLE product(
pID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pName VARCHAR(60) NOT NULL,
pPrice INT NOT NULL
);

CREATE TABLE orderdetail(
oID INT NOT NULL,
pID INT NOT NULL,
oQuantity INT NOT NULL,
PRIMARY KEY(oID,pID),
FOREIGN KEY(oID)
REFERENCES `order`(oID),
FOREIGN KEY(pID)
REFERENCES product(pID)

);